### ISSUE TITLE
Merging develop to master

### ISSUE THREAD

**Issue by thunderer** [golonka/BBCodeParser#33]
Hi, I sent you a PR #29 a couple of months ago and it was merged to `develop`. I saw that you released new version recently but it does not contain the changes from that PR. Could you please merge `develop` to `master` and possibly make a new release? If there is any problem with that, let me know how could I help. Thanks in advance.

**Comment by golonka** [comment]
No problem at all. My plan was just to release it as v3.0.0.
Mostly because it breaks some backwards compability, but also so I can make some parts better without having to worry about breaking stuff.

I don't have any time frame when it's going to be released. Just coding when I get some spare time.
